"""add payment table

Revision ID: 595ebc2d8a8f
Revises:
Create Date: 2025-10-27 23:12:57.161165

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "595ebc2d8a8f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tb_pagamento",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("id_externo", sa.String(), nullable=False),
        sa.Column(
            "st_pagamento",
            sa.Enum(
                "OPENED", "CLOSED", "EXPIRED", name="paymentstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("vl_total_pedido", sa.Float(), nullable=False),
        sa.Column("codigo_qr", sa.Text(), nullable=False),
        sa.Column("expiracao", sa.TIMESTAMP(), nullable=False),
        sa.Column("dt_inclusao", sa.TIMESTAMP(), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("id_externo"),
    )
    op.create_index(
        op.f("ix_tb_pagamento_st_pagamento"),
        "tb_pagamento",
        ["st_pagamento"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tb_pagamento_st_pagamento"), table_name="tb_pagamento")
    op.drop_table("tb_pagamento")
    # ### end Alembic commands ###
